name: release

on:
  push:
    branches:
      - 'master'

jobs:
  maven-release:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Unsnapshot version
        run:  mvn versions:set -DremoveSnapshot

      - id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$VERSION"
          FITNESSE_VERSION=$(mvn help:evaluate -Dexpression=fitnesse.version -q -DforceStdout)
          echo "::set-output name=fitnesse-version::$FITNESSE_VERSION"
          SELENIUM_VERSION=$(mvn help:evaluate -Dexpression=selenium.version -q -DforceStdout)
          echo "::set-output name=selenium-version::$SELENIUM_VERSION"

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_profiles: release
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.MAVEN_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_PASSWORD }}

      - name: Replace changelog placeholders
        uses: franzbischoff/replace_envs@v1
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
          FITNESSE_VERSION: ${{ steps.get-version.outputs.fitnesse-version }}
          SELENIUM_VERSION: ${{ steps.get-version.outputs.selenium-version }}
        with:
          from_file: './changelog.md'
          to_file: './changelog.md'
          commit: 'false'

      - name: Commit pom.xml without -SNAPSHOT
        run: |
          git config --global user.email "fhoeben-github@hsac.nl"
          git config --global user.name "GitHub Action"
          git add pom.xml
          git commit -m "Prepare for release"
          git push origin master

      - name: Create Release
        id: createRelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          body_path: './changelog.md'
          draft: false
          prerelease: false
          files: |
            target/hsac-fitnesse-fixtures-*.jar
            target/hsac-fitnesse-fixtures-*.zip

  update-version:
    needs: [maven-release]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Configure git
        run: |
          git config --global user.email "fhoeben-github@hsac.nl"
          git config --global user.name "GitHub Action"
      - name: Update version
        run: |
          mvn -B release:update-versions -DautoVersionSubmodules=true
          git add pom.xml
          git commit -m "Prepare for next developments"
          git push origin master
